version: '3.8'

services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog.Host/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5000
    ports:
        - 5000:5000

  nginx:
    image: nginx:latest
    ports:
        - 80:80
    # volumes:
        # - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
        # - ./Proxy/assets:/var/www/assets


networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4